#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the hourglassSum function below.
# https://www.hackerrank.com/challenges/2d-array/problem?h_l=interview&playlist_slugs%5B%5D%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D%5B%5D=arrays&isFullScreen=true
def hourglassSum(arr):
    high=-sys.maxsize
    Sum=0
    #print(high)
    for x in range(len(arr)-2):
        for y in range(len(arr[x])-2):
            Sum=arr[x][y]+arr[x][y+1]+arr[x][y+2]+arr[x+1][y+1]+arr[x+2][y]+arr[x+2][y+1]+arr[x+2][y+2]
            #print(Sum)
            if high < Sum:
                high = Sum
            #print(arr[x][y], end=', ')
        #print()
    return high
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
